spring:
  application:
    name: rpc_provider
  profiles:
    active: @profiles.active@
    include: mybatis, common
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  mvc:
    static-path-pattern: /static/**
#  web:
#    resources:
#      static-locations:

server:
  error:
    include-exception: true
    include-message: always

dubbo:
  scan:
    basePackages: com.zjy.rpc_provider.facade
  application:
    name: rpc_provider   #定义消费者名称
    owner: zjy
  protocol:
    port: -1
    name: dubbo
    dispatcher: message
  provider:
    filter: exceptionFilter
    timeout: 10000
  consumer:
    timeout: 10000