spring:
  datasource:
    master:
      driver-class-name: org.sqlite.JDBC
      password:
      jdbcUrl: jdbc:sqlite://D:/workspace/code/my/java_ToolSiteMvc4J/web/target/classes/db/app.db
      username:
    slave:
      driver-class-name: org.sqlite.JDBC
      password:
      jdbcUrl: jdbc:sqlite://D:/workspace/code/my/java_ToolSiteMvc4J/web/target/classes/db/app.db
      username:
    migration:
      driver-class-name: org.sqlite.JDBC
      password:
      jdbcUrl: jdbc:sqlite://D:/workspace/code/my/java_ToolSiteMvc4J/web/target/classes/db/app.db
      username:

#mybatis:
#  configuration:
#    map-underscore-to-camel-case: true
#    lazy-loading-enabled: false
#    interceptors: com.zjy.dao.common.sql.SqlPrint

#mybatis-plus:
#  configuration:
#    map-underscore-to-camel-case: false
##    interceptors: com.zjy.dao.common.sql.SqlPrint
#    lazy-loading-enabled: false

pagehelper:
  helperDialect: sqlite