spring:
  profiles:
    include: mybatis, common
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

server:
  error:
    include-exception: true
    include-message: always
  port: 8088