spring:
  profiles:
    active: @profiles.active@
    include: mybatis, common
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  mvc:
    static-path-pattern: /static/**

#  web:
#    resources:
#      static-locations:

#  redis:
#    host: 127.0.0.1

server:
  error:
    include-exception: true
    include-message: always
  port: 8088

ttkey:
  ab: @mykey@