server:
  port: 8088

spring:
  redis:
    host: 127.0.0.1
    port: 6379

mykey1: in dev profile

mykey2:
  ab: @mykey@

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    prometheus:
      enabled: true
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true