spring:
  application:
    name: mymvc
  profiles:
    active: @profiles.active@
    include: mybatis, common
  messages:
    basename: i18n/messages
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  mvc:
    static-path-pattern: /static/**
#  web:
#    resources:
#      static-locations:

server:
  error:
    include-exception: true
    include-message: always