spring:
  profiles:
    include: mybatis, common
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
#  redis:
#    host: 127.0.0.1

server:
  error:
    include-exception: true
    include-message: always
  port: 8088